[package]
name = "tracky"
version = "0.1.0"
authors = ["Martin Hochstrasser <highstreeto@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0"