[package]
name = "tracky"
version = "0.1.0"
authors = ["Martin Hochstrasser <martin.hochstrasser@gmx.at>"]
edition = "2018"

[dependencies]
colored = "1.7.0"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0"
