[package]
name = "tracky-gui"
version = "0.1.0"
authors = ["Martin Hochstrasser <highstreeto@users.noreply.github.com>"]
edition = "2018"

[dependencies]
azul = { git = "https://github.com/maps4print/azul" }
